version: '3'

services:
  parakeet:
    build: .
    volumes:
      - ./parakeet-tdt-0.6b-v2:/app/parakeet-tdt-0.6b-v2
      - ./input:/app/input
      - ./output:/app/output
    # Removing GPU requirements for macOS compatibility
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu] 